### ISSUE TITLE
Missing thubmnail.png on the root folder

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/forge-digital-catalog#1]
Samples should have a thumbnail image at the repo root folder, this image is used by [Forge Dev Portal listing](https://forge.autodesk.com/code-samples) automatically. You can either move or copy one of the existing images, make sure to rename to `thumbnail.png` (or `.gif` for animated)

**Comment by mazerab** [comment]
@augustogoncalves New thumbnail GIF file is now in root folder: https://github.com/Autodesk-Forge/forge-digital-catalog/blob/master/thumbnail.gif.
